<template>
  <div class="bg-layer" :style="[cssVars, isPattern ? {} : styleObject]">
    <!-- eslint-disable-next-line vue/no-v-html -- svgMarkup is generated by the preset registry, never user input -->
    <div v-if="isPattern" class="bg-layer__pattern" v-html="svgMarkup"></div>
    <!-- eslint-disable-next-line vue/no-v-html -- filterDef is generated by the preset registry, never user input -->
    <div v-if="filterDef" class="bg-layer__filter-defs" v-html="filterDef"></div>
  </div>
</template>

<script setup lang="ts">
import { computed, toRef } from "vue";
import { useAnimatedBackground } from "./useAnimatedBackground";
import { getBackgroundPreset, type BackgroundConfig } from "./backgrounds";

const props = defineProps<{
  config: BackgroundConfig;
}>();

const configRef = toRef(props, "config");
const { cssVars, styleObject, svgMarkup, filterDef } =
  useAnimatedBackground(configRef);

const isPattern = computed(
  () => getBackgroundPreset(props.config.presetId)?.category === "pattern",
);
</script>

<style scoped>
.bg-layer {
  position: absolute;
  inset: 0;
  overflow: hidden;
  pointer-events: none;
}

.bg-layer__pattern {
  position: absolute;
  inset: 0;
}

.bg-layer__pattern :deep(svg) {
  display: block;
  width: 100%;
  height: 100%;
}

.bg-layer__filter-defs {
  position: absolute;
  width: 0;
  height: 0;
  overflow: hidden;
}
</style>
