import type { RoadmapDao } from "@grids/contracts/dao";
import type { FetchRoadmapResult, NotionDatabase } from "@grids/contracts/types";
import type { RoadmapQueryFilter } from "@grids/contracts/types";

export class StubbedRoadmapDao implements RoadmapDao {
  public async listDatabases(
    _gridId: string,
    _tileId: string,
  ): Promise<NotionDatabase[]> {
    return [
      {
        id: "stubbed-roadmap-database",
        title: "Stubbed roadmap",
      },
    ];
  }

  public async fetchRoadmap(
    _gridId: string,
    _tileId: string,
    _queryFilters?: RoadmapQueryFilter[],
    _databaseIdOverride?: string,
  ): Promise<FetchRoadmapResult> {
    return {
      items: [
        {
          notionPageId: "stubbed-roadmap-backlog",
          title: "Plan local-only experience",
          status: "backlog",
          description: "This sample item is generated by the in-memory stub.",
          upvoteCount: 0,
        },
        {
          notionPageId: "stubbed-roadmap-progress",
          title: "Run without cloud services",
          status: "in_progress",
          description: "Roadmap data is temporary and resets on refresh.",
          upvoteCount: 0,
        },
      ],
      propertyOptions: [
        {
          name: "Status",
          type: "status",
          selectOptions: ["Backlog", "In Progress", "Done"],
        },
      ],
    };
  }
}
